services:
  nginx:
    container_name: nginx_prod
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./:/var/www/html
      # - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    restart: unless-stopped

  php:
    container_name: php_prod
    restart: unless-stopped
    # Don't mount volumes in production for security
    volumes: []

  mysql:
    container_name: mysql_prod
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./docker/mysql/backup:/backup